# Uncomment this line to define a global platform for your project
platform :ios, "5.1"           

xcodeproj 'CRPullDownToRefreshDemo'
workspace 'CRPullDownToRefreshDemo'

pod 'CRPullDownToRefresh', :path => '..'                                                                                                                                          
